# services:
#   postgres:
#     image: postgres:15
#     environment:
#       - POSTGRES_PASSWORD=temporal
#       - POSTGRES_USER=temporal
#     ports:
#       - '5432:5432'
#     volumes:
#       - temporal-postgres-data:/var/lib/postgresql/data

#   temporal:
#     image: temporalio/auto-setup:1.25.1
#     environment:
#       - DB=postgresql
#       - DB_PORT=5432
#       - POSTGRES_USER=temporal
#       - POSTGRES_PWD=temporal
#       - POSTGRES_SEEDS=postgres
#       - DYNAMIC_CONFIG_FILE_PATH=config/dynamicconfig/development.yaml
#     ports:
#       - '7233:7233'
#     depends_on:
#       - postgres
#     healthcheck:
#       test: ['CMD', 'tctl', '--address', 'temporal:7233', 'workflow', 'list']
#       interval: 10s
#       timeout: 5s
#       retries: 10

#   temporal-ui:
#     image: temporalio/ui:2.25.0
#     environment:
#       - TEMPORAL_ADDRESS=temporal:7233
#     ports:
#       - '8080:8080'
#     depends_on:
#       - temporal

# volumes:
#   temporal-postgres-data:




services:
  postgres:
    image: postgres:15
    environment:
      - POSTGRES_PASSWORD=temporal
      - POSTGRES_USER=temporal
    ports:
      - '5432:5432'
    volumes:
      - temporal-postgres-data:/var/lib/postgresql/data

  temporal:
    image: temporalio/auto-setup:1.25.1
    platform: linux/amd64
    environment:
      - DB=postgresql
      - DB_PORT=5432
      - POSTGRES_USER=temporal
      - POSTGRES_PWD=temporal
      - POSTGRES_SEEDS=postgres
      - DYNAMIC_CONFIG_FILE_PATH=config/dynamicconfig/development.yaml
    ports:
      - '7233:7233'   # external:internal
    depends_on:
      - postgres
    healthcheck:
      test: ['CMD', 'tctl', '--address', 'temporal:7233', 'workflow', 'list']
      interval: 10s
      timeout: 5s
      retries: 10

  temporal-ui:
    image: temporalio/ui:2.25.0
    environment:
      - TEMPORAL_ADDRESS=temporal:7233
    ports:
      - '8080:8080'
    depends_on:
      - temporal

volumes:
  temporal-postgres-data:
